### ISSUE TITLE
Possible New Bot Feature

### ISSUE THREAD

**Issue by ArelySkywalker** [SaraTorrey/women-coders-bot#2]
Found your bot from it retweeting one of my tweets, I love it! 😊

Is this strictly a retweet bot? If not, I would love to fork this repo and add a feature to where it listens for your current hashtags + #100DaysOfCode, and it replies to the user with motivational tweets such as:

`String motivationalExample[] = { "Keep up the good work!", "Great work!", "You are awesome!", "You go girl! 💪" };`

Love your bot, keep on coding! ❤️

**Comment by WTobor** [comment]
Sounds great!
